name: Run Cypress Tests and Postman API Tests

on:
  push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set Testomat API Key
        run: echo "TESTOMATIO=tstmt_jD8Ba7Y6MEdfz6GSfNPuPkZdm-iXkSli8g1723767529" >> $GITHUB_ENV

      - name: Import Test Data to Testomat
        run: |
          echo "Importing test data to Testomat..."
          export TESTOMATIO=tstmt_jD8Ba7Y6MEdfz6GSfNPuPkZdm-iXkSli8g1723767529
          npx check-tests@latest Cypress.io "**/*{.,_}{test,spec,cy}.js" --dir cypress/

      - name: Install Testomat Reporter
        run: |
          echo "Installing Testomat Reporter..."
          npm install --save-dev @testomatio/reporter

      - name: Run Tests on Testomat
        run: |
          echo "Running tests on Testomat..."
          export TESTOMATIO=tstmt_jD8Ba7Y6MEdfz6GSfNPuPkZdm-iXkSli8g1723767529
          npx cypress run

      - name: Run Cypress Tests Locally
        run: |
          echo "Running Cypress tests locally..."
          npx cypress run

      - name: Install Newman and Reporters
        run: |
          echo "Installing Newman and reporters..."
          npm install -g newman-reporter-html extra

      - name: Run Postman API Tests
        run: |
          echo "Running Postman API tests..."
          mkdir -p postman-reports
          newman run Yuzee_Log_in_API.postman_collection.json --reporters cli,htmlextra --reporter-htmlextra-export postman-reports/report.html

      - name: List Files
        run: |
          echo "Listing files in the postman-reports directory..."
          ls -la postman-reports

      - name: Upload Cypress Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report
          path: cypress/reports
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Postman Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: postman-report
          path: postman-reports/report.html
          retention-days: 30
          if-no-files-found: ignore
