name: Run Cypress Tests

on:
  push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set Testomat API Key
        run: echo "TESTOMATIO=tstmt_jD8Ba7Y6MEdfz6GSfNPuPkZdm-iXkSli8g1723767529" >> $GITHUB_ENV

      - name: Import Test Data to Testomat
        run: |
          echo "Importing test data to Testomat..."
          export TESTOMATIO=tstmt_jD8Ba7Y6MEdfz6GSfNPuPkZdm-iXkSli8g1723767529
          npx check-tests@latest Cypress.io "**/*{.,_}{test,spec,cy}.js" --dir cypress/

      - name: Install Testomat Reporter
        run: |
          echo "Installing Testomat Reporter..."
          npm install --save-dev @testomatio/reporter

      - name: Run Tests on Testomat
        run: |
          echo "Running tests on Testomat..."
          export TESTOMATIO=tstmt_jD8Ba7Y6MEdfz6GSfNPuPkZdm-iXkSli8g1723767529

      - name: Run Cypress Tests Locally
        run: |
          echo "Running Cypress tests locally..."
          npm test

      - name: Upload Cypress Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports
          if-no-files-found: ignore

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always() # Ensure screenshots are uploaded regardless of test success/failure
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always() # Ensure videos are uploaded regardless of test success/failure
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore