name: Run Cypress Tests and Publish Report

on:
  repository_dispatch:
    types: [bitbucket_pr_trigger]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run

      - name: Upload Cypress Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report
          path: cypress/reports
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 30
          if-no-files-found: ignore

      - name: Commit Report to Bitbucket
        env:
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
        run: |
          echo "Debug: Start committing report to Bitbucket"

          # Set Git user details
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config user.email "ub5fjhx5cudmtxol9d4y1c8rjqr71t@bots.bitbucket.org"

          echo "Debug: Cloning repository"
          git clone https://x-token-auth:${BITBUCKET_TOKEN}@bitbucket.org/thabit1/prapplicationtesting.git reports || echo "Cloning failed"

          echo "Debug: Copying reports"
          cp -r cypress/reports/* reports/

          cd reports

          echo "Debug: Status of git repository"
          git status

          echo "Debug: Adding files"
          git add .

          echo "Debug: Committing changes"
          git commit -m "Update Cypress HTML report" || echo "No changes to commit"

          echo "Debug: Pushing changes"
          git push origin main || echo "Push failed"
