name: Run Cypress Tests

on:
  repository_dispatch:
    types: [bitbucket_pr_trigger]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or '16' if you prefer Node.js 16

      - name: Install dependencies
        run: npm install

      - name: Install Cypress Mochawesome Reporter
        run: npm install cypress-mochawesome-reporter --save-dev

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Generate report
        run: npm run cypress:report

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports