name: Run Cypress Tests

on:
  repository_dispatch:
    types: [bitbucket_pr_trigger]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run

      - name: Convert HTML Report to PDF
        run: |
          npm install -g puppeteer
          node -e "
            const puppeteer = require('puppeteer');
            (async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.goto('file:///home/runner/work/applicationtests/applicationtests/cypress/reports/index.html', {waitUntil: 'networkidle2'});
              await page.pdf({ path: '/home/runner/work/applicationtests/applicationtests/cypress/reports/report.pdf', format: 'A4' });
              await browser.close();
            })();
          "

      - name: Upload PDF Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report-pdf
          path: cypress/reports/report.pdf
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 30
          if-no-files-found: ignore

      - name: Commit Report to Bitbucket
        env:
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --branch reports https://thabit1-admin:${BITBUCKET_TOKEN}@bitbucket.org/thabit1/prapplicationtesting.git reports || git clone https://thabit1-admin:${BITBUCKET_TOKEN}@bitbucket.org/thabit1/prapplicationtesting.git reports
          cp -r cypress/reports/* reports/
          cd reports
          git add .
          git commit -m "Update Cypress HTML report and PDF" || echo "No changes to commit"
          git push origin reports
