name: Run Cypress Tests

on:
  repository_dispatch:
    types: [bitbucket_pr_trigger]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Testomat Reporter
        run: npm install --save-dev @testomatio/reporter

      - name: Import Data to Testomat
        env:
          TESTOMATIO: ${{ secrets.TESTOMATIO_API_KEY }}
        run: npx check-tests@latest Cypress.io "**/*{.,_}{test,spec,cy}.js" --dir cypress/*

      - name: Run Cypress Tests
        env:
          TESTOMATIO: ${{ secrets.TESTOMATIO_API_KEY }}
        run: npx cypress run

      - name: Upload Cypress Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report
          path: cypress/reports
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 30
          if-no-files-found: ignore