name: Run Cypress Tests on Time

on:
  schedule:
    - cron: '24 20 * * *'  # Runs at 12:25 PM UTC, which is 8:25 PM in Malaysia

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run

      - name: Upload Cypress Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report
          path: cypress/reports
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 30
          if-no-files-found: ignore

      - name: Commit Report, Screenshots, and Videos to Bitbucket
        if: always()
        env:
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --branch reports https://thabit1-admin:${BITBUCKET_TOKEN}@bitbucket.org/thabit1/prapplicationtesting.git reports || git clone https://thabit1-admin:${BITBUCKET_TOKEN}@bitbucket.org/thabit1/prapplicationtesting.git reports
          mkdir
